### ISSUE TITLE
MabiPack not writing version info

### ISSUE THREAD

**Issue by jiaaluo** [logue/MabiPack#5]
As mentioned versions don't seem to be written anymore.

No matter what the input is only 1 seems to be written as a pack version.

**Comment by logue** [comment]
Same problem as #4.

**Comment by jiaaluo** [comment]
I'm confused to how this is related to issue #4 I use the command line utility so I should be unaffected.
This issue has persisted for quite some time, before the servers switched to a different service.

**Comment by logue** [comment]
Do you mean version.dat instead of the package version?
If you mean the version of the * .pack file, has the read-only attribute been added to the generated * .pack file?
On the client's specifications, if you do not use a third-party launcher such as MabiLauncher Plus and PowerPatcher, they will be deleted and not keep with the read-only attribute to the generated pack file.

https://mabiassist.logue.be/MabiPacker#y5e92a1e

**Comment by jiaaluo** [comment]
I meant the pack version in the .pack, I assumed version wrote to .pack
An example of a .pack from one of the servers.
https://i.imgur.com/Ivy3haM.png
This is what it looks like when it is generated from mabipacker
https://i.imgur.com/fO1oNBY.png
It would always have a version number of 1

**Comment by logue** [comment]
This is not a problem with MabiPacker but with [MabinogiResource[(https://github.com/logue/MabinogiResource).

I am not familiar with C language so I can not cope with it. 
Probably there is a defect in the following function.

https://github.com/logue/MabinogiResource/blob/10fb5f387eb7ce44fefd03c89f69ec94a6d4f71e/MabinogiResource/PackResourceSet.cpp#L49-L169
https://github.com/logue/MabinogiResource/blob/10fb5f387eb7ce44fefd03c89f69ec94a6d4f71e/MabinogiResource/Utility.cpp#L41-L49

**Comment by logue** [comment]
This is bug of [MabinogiResource](https://github.com/logue/MabinogiResource).

Please replace MabinogiResource.net.dl to this dll.
[MabinogiResource.net-108.zip](https://github.com/logue/MabiPack/files/3316610/MabinogiResource.net-108.zip)
